include ./theme.conf
font_family    Space Mono for Powerline
bold_family    Space Mono for Powerline Bold
italic_family  Space Mono for Powerline Italic
bold_italic_family  Space Mono for Powerline Bold Italic

font_size 12
background_opacity 0.75
